# NumPy Notebook by Divyanshu
NumPy is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. It contains among other things:

# importing numpy


In [3]:
import numpy as np

In [19]:
#all numpy elements
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [5]:
#Declaring array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
b =np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(3,)

In [7]:
b.dtype

dtype('int32')

In [9]:
b.shape

(2, 3)

In [10]:
print(type(b))

<class 'numpy.ndarray'>


In [13]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#range of 10-20 
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
#range of 10-20 with a gap of 2
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [24]:
c=np.array([[1,2,3],[6,9,8,7],[2,9,8]])
c

array([list([1, 2, 3]), list([6, 9, 8, 7]), list([2, 9, 8])], dtype=object)

In [28]:
#loop time
c=range(10000)
%timeit [i**3 for i in c]

9.15 ms ± 142 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
#multiplication of 5 in all array elements
l = [1,5,8,9]
[i*5 for i in l ]

[5, 25, 40, 45]

In [31]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

50.9 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
x= np.arange(10)
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [34]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [39]:
np.full((7,6),8.9, dtype= np.int)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [40]:
np.full((7,6),8.9)

array([[8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9]])

In [41]:
v = np.array([1,2,3])
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
v = np.array([1,2,3])
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [43]:
np.random.random()

0.6098805994713034

In [45]:
50*np.random.random([3,3])+2

array([[24.20792219,  3.21074371,  9.46033307],
       [ 6.9675814 , 21.69734293, 15.2610495 ],
       [ 9.10952589, 42.86747065,  8.32075249]])

In [46]:
np.random.random([3,3])

array([[0.01739097, 0.31585357, 0.87017604],
       [0.85782003, 0.01094715, 0.68953474],
       [0.50561407, 0.30825093, 0.54945589]])

In [51]:
# 1-50 random elements(100) 
a= np.linspace(1,50,100)
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [52]:
a.itemsize
a.shape

(100,)

In [53]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [63]:
#reshaping array
np.arange(18).reshape(9,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [64]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a=b

In [66]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
#condition checking
a==b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [8]:
v=([1,2,3,4,5,6])


In [9]:
q=([9,8,7,4,5,6])

In [10]:
v==q

False

In [11]:
data=([[1,2,3],[4,5,6]])
data2d=np.array(data)
data

[[1, 2, 3], [4, 5, 6]]

In [16]:
# create a 2D numpy array
data=([[1,2,3],[4,5,6]])
data2d=np.array(data)
data2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [18]:
data2d + data2d
data2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
v=[1,2,3,4,5,6]

In [24]:
print(v)

[1, 2, 3, 4, 5, 6]


In [26]:
# method to find mean
np.mean(v)

3.5

In [27]:
# method to find dot product
np.dot(v, v)

91

In [30]:
# element-wise multiplication
data2d * data2d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
# element-wise addition
data2d + data2d

array([[ 2,  4,  6],
       [ 8, 10, 12]])

# Indexing and Slicing
Numpy follows Python's rules "Includes the first" and "Excludes the last" :

In [33]:
# access from first to third
v[1: 3]

[2, 3]

In [34]:
# access from second to last
v[1:]

[2, 3, 4, 5, 6]

In [35]:
# row 1, all columns
data2d[1,:2]

array([4, 5])